/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/basics/About.vue')['default']
    Awards: typeof import('./src/components/awards/Awards.vue')['default']
    Basics: typeof import('./src/components/basics/Basics.vue')['default']
    Certificates: typeof import('./src/components/certificates/Certificates.vue')['default']
    Collapse: typeof import('./src/components/common/Collapse.vue')['default']
    Description: typeof import('./src/components/common/Description.vue')['default']
    Duration: typeof import('./src/components/common/Duration.vue')['default']
    Education: typeof import('./src/components/education/Education.vue')['default']
    EducationCard: typeof import('./src/components/education/EducationCard.vue')['default']
    'IMaterialSymbols:locationOn': typeof import('~icons/material-symbols/location-on')['default']
    'IMaterialSymbols:phoneEnabled': typeof import('~icons/material-symbols/phone-enabled')['default']
    'IMdi:accountCircle': typeof import('~icons/mdi/account-circle')['default']
    'IMdi:calendar': typeof import('~icons/mdi/calendar')['default']
    'IMdi:circle': typeof import('~icons/mdi/circle')['default']
    'IMdi:email': typeof import('~icons/mdi/email')['default']
    'IMdi:loading': typeof import('~icons/mdi/loading')['default']
    'IMdi:star': typeof import('~icons/mdi/star')['default']
    'IMdi:trophy': typeof import('~icons/mdi/trophy')['default']
    'IMdi:web': typeof import('~icons/mdi/web')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    Interests: typeof import('./src/components/interests/Interests.vue')['default']
    Languages: typeof import('./src/components/languages/Languages.vue')['default']
    Loading: typeof import('./src/components/common/Loading.vue')['default']
    Location: typeof import('./src/components/common/Location.vue')['default']
    Ongoing: typeof import('./src/components/common/Ongoing.vue')['default']
    ProfileIcons: typeof import('./src/components/basics/ProfileIcons.vue')['default']
    ProjectCard: typeof import('./src/components/projects/ProjectCard.vue')['default']
    Projects: typeof import('./src/components/projects/Projects.vue')['default']
    Publications: typeof import('./src/components/publications/Publications.vue')['default']
    References: typeof import('./src/components/references/References.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionBox: typeof import('./src/components/common/SectionBox.vue')['default']
    SectionComponentIs: typeof import('./src/components/common/SectionComponentIs.vue')['default']
    Skills: typeof import('./src/components/skills/Skills.vue')['default']
    Tag: typeof import('./src/components/common/Tag.vue')['default']
    Volunteer: typeof import('./src/components/volunteer/Volunteer.vue')['default']
    Work: typeof import('./src/components/work/Work.vue')['default']
    WorkCard: typeof import('./src/components/work/WorkCard.vue')['default']
  }
}
